### ISSUE TITLE
Custom fonts only works on BF4.4

### ISSUE THREAD

**Issue by lesharodin** [hd-zero/hdzero-osd-font-library#11]
Seems like 4.3.0 BF didn't get recognized when using custom fonts.
Have 2 quads, applied custom font to SharkByte VRX.
On 4.3 - stock font
On 4.4RC1 - custom font

Since we dont have VRX repo is it right place to report this Issue?

**Comment by ondrascz** [comment]
I have been testing custom fonts on VRX-4. FC runs BF 4.3.1. Custom fonts are working perfectly even though I didn't updated FW in the VTX (Race V2)

**Comment by lesharodin** [comment]
More info in previous issue
