### ISSUE TITLE
INAV OSD file doesn't work 

### ISSUE THREAD

**Issue by DanO83** [hd-zero/hdzero-osd-font-library#15]
the INAV OSD file doesn't work, I have made a Resource directory on my sdcard and copied the file to this directory. Then renamed it to FC_VARIANT.bmp.

The OSD was the same as without the bmp file.

Did anyone tested these files ?

**Comment by lesharodin** [comment]
You need rename it to `INAV6.bmp` or `INAV5.bmp `

**Comment by DanO83** [comment]
I have just tried that, but still no change. Also if this is the the way files should be named maybe someone can change the instructions to make it better understandable.

**Comment by DanO83** [comment]
I also noticed that the layout of the bmp image files are very different then the betaflight files. Shouldn't they be more alike ?

**Comment by ligenxxxx** [comment]
It should be renamed "INAV.bmp".

**Comment by ondrascz** [comment]
There are two options of the glyph spacing in the bmp. 0px and 6px. You can chose any of them for any fc variant.

**Comment by DanO83** [comment]
I have changed the file name to "INAV.bmp", now it's working fine.

There is another issue, I have to go to the menu first to make the new OSD fonts active. But that's probably a firmware issue with the VRX4. This is already reported

**Comment by ondrascz** [comment]
VRX4 doesn't have this issue (at least mine doesn't). It's reported for ShaBy VRX

**Comment by DanO83** [comment]
I have a VRX4 on firmware 40.2A.4C, and it has this issue. I have to go to the menu and back first see the new fonts

**Comment by ondrascz** [comment]
That is weird. I have the same. The custom font is always loaded during a boot. No need to enter the menu. A few thing come to my mind:
* does your VRX boot to a pre selected channel or to auto scan? (Mine boot to a channel)
* is your VTX transmitting before the VRX boots? (Mine is not, I always turn on the VTX later using AUX)

**Comment by DanO83** [comment]
I tried to boot it with a selected channel and I tried booting with auto scan.

Also I tried powering the vtx first (then wait a few seconds) then the vrx and the other way around.

Also tried reformatting the sd card in the vtx

nothing helps, I still need to go into the menu to activate the fonts.

**Comment by ondrascz** [comment]
I assume you have only INAV.bmp file in the resource folder. Did you try to copy BTFL.bmp there also?

**Comment by DanO83** [comment]
I tried to also copy a BTFL.bmp file to the sdcard.
This is clearing up things.

Now it looks like the BTFL.bmp is loaded when powering up the vrx. It shows a different osd then stock, but it's a bit messed up with parts of the betaflight logo showing. When I go to the menu and back the INAV.bmp is showing.

so to work around having to go to the menu to get the right osd fonts I have copied the INAV.bmp to the BTFL.bmp file so there both contains the inav font file.

There must be something wrong with the vrx firmware, it probably looks for a BTFL.bmp file at boot

**Comment by ondrascz** [comment]
The messed up BF logo is probably caused by the fact you are not using BF 4.4.0 and HD OSD

**Comment by DanO83** [comment]
Yes i know that the osd is messed up because i'm not using betaflight at all, i'm only using inav.
but it shows how the vrx firmware always wanting to use the BTFL.bmp at startup, no matter if there is an INAV.bmp present in de Resource directory
